[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
ignored_warnings_from = ["dependencies/", "src/token/OUSD.sol"]

# Remappings
auto_detect_remappings = false
remappings = [
  "forge-std/=dependencies/forge-std-1.9.6/src/",
  "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-4.4.1-4.4.1/contracts/",
  "@openzeppelin-4.6.0/contracts/=dependencies/@openzeppelin-contracts-4.6.0-4.6.0/contracts/",
]

[dependencies]
forge-std = "1.9.6"
"@openzeppelin-contracts-4.4.1" = { version = "4.4.1", git = "https://github.com/OpenZeppelin/openzeppelin-contracts.git", rev = "6bd6b76d1156e20e45d1016f355d154141c7e5b9" }
"@openzeppelin-contracts-4.6.0" = { version = "4.6.0", git = "https://github.com/OpenZeppelin/openzeppelin-contracts.git", rev = "d4fb3a89f9d0a39c7ee6f2601d33ffbf30085322" }

[soldeer]
recursive_deps = false
remappings_version = false
remappings_generate = false
remappings_regenerate = false
remappings_prefix = "@"
remappings_location = "config"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
