[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]

# Remappings
auto_detect_remappings = false
remappings = [
  "forge-std/=dependencies/forge-std-1.9.6/src/",
  "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-4.4.1/",
]

[dependencies]
forge-std = "1.9.6"
"@openzeppelin-contracts" = "4.4.1"

[soldeer]
recursive_deps = false
remappings_version = false
remappings_generate = false
remappings_regenerate = false
remappings_prefix = "@"
remappings_location = "config"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
